# General Jekyll Config
pygments: true
url: http://blog.multilatex.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink: /:title

theme:
  title: Multilatex
  name: Paul Nechifor
  email: paul@nechifor.net
  website: http://nechifor.net
  tagline: "Building a collaborative web Latex editor."
  social:
    github: paul-nechifor
  # Color for top bar, links, etc
  highlight_color: '#3498db'

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://blog.multilatex.com
