# General Jekyll Config
pygments: true
urlRoot: http://multilatex.com
url: http://multilatex.com/blog
lsi: false
exclude: [README.md, .gitignore, Makefile]
permalink: /blog/:title

theme:
  title: Multilatex
  name: Paul Nechifor
  email: paul@nechifor.net
  website: http://nechifor.net
