# General Jekyll Config
pygments: true
url: http://multilatex.com/blog
lsi: false
permalink: /blog-data/posts/:title.html

theme:
  title: Multilatex
  name: Paul Nechifor
  email: paul@nechifor.net
  website: http://nechifor.net
  tagline: "Building a collaborative web Latex editor."
